# Laboratorio Python Maestría Doctorado UNITEC 2025
## Semana 3 -
### Post-Class Jupyeter

```
# Esto tiene formato de código
```

 Notebook


------------

# Creando dataframes con diccionarios

In [42]:
students = {'FIRST_NAME' : ['Daniel', 'Ben', 'Kavita', 'Linda', 'Omar', 'Jane', 'Felicia', 'Rachel', 'Bob'],
            'LAST_NAME'  : ['Smith', 'Leibstrom', 'Kanabar', 'Thiel', 'Reichel', 'OConner', 'Rao', 'Crock', 'McDonald'],
            'YEAR' : [1, 1, 1, 4, 2, 2, 3, 1, 1],
            'HOME_STATE' : ['NY', 'NY', 'PA', 'CA', 'OK', 'HI', 'NY', 'FL', 'FL'],
            'AGE' : [18, 19, 19, 22, 21, 19, 20, 17, 18],
            'CALC_101_FINAL' : [90, 80, None, 60, 70, None, None, None, 98],
            'ENGLISH_101_FINAL' : [80, None, None, 40, 50, None, None, 60, 65]}

In [25]:
new_census_cols = ['FIPS', 'GEOGRAPHY', 'POPULATION', 'MEDIAN_AGE',
                       'TOTAL_HOUSEHOLD', 'MEDIAN_HH_INCOME',
                       'AV_HH_SIZE', 'TOTAL_FAMILIES', 'AV_FAMILY_SIZE',
                       'PERC_OWNER_OCCUPIED_HOUSING', 'PERC_RENTER_OCCUPIED_HOUSING',
                       'POP_16_AND_OVER', 'UNEMPLOYMENT_RATE']

# Pandas Series and Dataframes

In [43]:
# Import the Pandas library, and refer to it as pd from
# now on
import pandas as pd

In [26]:
df_students = pd.DataFrame(students)
df_students

,FIRST_NAME,LAST_NAME,YEAR,HOME_STATE,AGE,CALC_101_FINAL,ENGLISH_101_FINAL
0,Daniel,Smith,1,NY,18,90.0,80.0
1,Ben,Leibstrom,1,NY,19,80.0,NaN
2,Kavita,Kanabar,1,PA,19,NaN,NaN
3,Linda,Thiel,4,CA,22,60.0,40.0
4,Omar,Reichel,2,OK,21,70.0,50.0
5,Jane,OConner,2,HI,19,NaN,NaN
6,Felicia,Rao,3,NY,20,NaN,NaN
7,Rachel,Crock,1,FL,17,NaN,60.0
8,Bob,McDonald,1,FL,18,98.0,65.0

In [44]:
# Access the FIRST_NAME column
df_students['FIRST_NAME']

0     Daniel
1        Ben
2     Kavita
3      Linda
4       Omar
5       Jane
6    Felicia
7     Rachel
8        Bob
Name: FIRST_NAME, dtype: object

In [45]:
# Or use the . notation
df_students.FIRST_NAME

0     Daniel
1        Ben
2     Kavita
3      Linda
4       Omar
5       Jane
6    Felicia
7     Rachel
8        Bob
Name: FIRST_NAME, dtype: object

In [46]:
i = 'HOME_STATE'
df_students[i]

0    NY
1    NY
2    PA
3    CA
4    OK
5    HI
6    NY
7    FL
8    FL
Name: HOME_STATE, dtype: object

In [47]:
# Access a column whose name is in a variable
i = 'HOME_STATE'
df_students[i]

0    NY
1    NY
2    PA
3    CA
4    OK
5    HI
6    NY
7    FL
8    FL
Name: HOME_STATE, dtype: object

In [48]:
# Extract a dataframe with a single column
df_students[ ['FIRST_NAME'] ]

  FIRST_NAME
0     Daniel
1        Ben
2     Kavita
3      Linda
4       Omar
5       Jane
6    Felicia
7     Rachel
8        Bob

In [49]:
# Select only some of the columns in our data
df_students[['FIRST_NAME', 'LAST_NAME']]

  FIRST_NAME  LAST_NAME
0     Daniel      Smith
1        Ben  Leibstrom
2     Kavita    Kanabar
3      Linda      Thiel
4       Omar    Reichel
5       Jane    OConner
6    Felicia        Rao
7     Rachel      Crock
8        Bob   McDonald

In [50]:
df_students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   FIRST_NAME         9 non-null      object
 1   LAST_NAME          9 non-null      object
 2   YEAR               9 non-null      int64
 3   HOME_STATE         9 non-null      object
 4   STUD_AGE           9 non-null      int64
 5   CALC_101_FINAL     5 non-null      float64
 6   ENGLISH_101_FINAL  5 non-null      float64
dtypes: float64(2), int64(2), object(3)
memory usage: 636.0+ bytes

In [51]:
# Exercise
df_students[['FIRST_NAME', 'LAST_NAME', 'YEAR']]

  FIRST_NAME  LAST_NAME  YEAR
0     Daniel      Smith     1
1        Ben  Leibstrom     1
2     Kavita    Kanabar     1
3      Linda      Thiel     4
4       Omar    Reichel     2
5       Jane    OConner     2
6    Felicia        Rao     3
7     Rachel      Crock     1
8        Bob   McDonald     1

# Columnas y filas

In [52]:
# View the columns in df_students
df_students.columns

Index(['FIRST_NAME', 'LAST_NAME', 'YEAR', 'HOME_STATE', 'STUD_AGE',
       'CALC_101_FINAL', 'ENGLISH_101_FINAL'],
      dtype='object')

In [53]:
# Rename a column
df_students.rename(columns = {'AGE':'STUDENT_AGE'})

,FIRST_NAME,LAST_NAME,YEAR,HOME_STATE,STUD_AGE,CALC_101_FINAL,ENGLISH_101_FINAL
0,Daniel,Smith,1,NY,18,90.0,80.0
1,Ben,Leibstrom,1,NY,19,80.0,NaN
2,Kavita,Kanabar,1,PA,19,NaN,NaN
3,Linda,Thiel,4,CA,22,60.0,40.0
4,Omar,Reichel,2,OK,21,70.0,50.0
5,Jane,OConner,2,HI,19,NaN,NaN
6,Felicia,Rao,3,NY,20,NaN,NaN
7,Rachel,Crock,1,FL,17,NaN,60.0
8,Bob,McDonald,1,FL,18,98.0,65.0

In [54]:
# Rename a column and save it
df_students = df_students.rename(columns = {'AGE':'STUDENT_AGE'})
df_students

,FIRST_NAME,LAST_NAME,YEAR,HOME_STATE,STUD_AGE,CALC_101_FINAL,ENGLISH_101_FINAL
0,Daniel,Smith,1,NY,18,90.0,80.0
1,Ben,Leibstrom,1,NY,19,80.0,NaN
2,Kavita,Kanabar,1,PA,19,NaN,NaN
3,Linda,Thiel,4,CA,22,60.0,40.0
4,Omar,Reichel,2,OK,21,70.0,50.0
5,Jane,OConner,2,HI,19,NaN,NaN
6,Felicia,Rao,3,NY,20,NaN,NaN
7,Rachel,Crock,1,FL,17,NaN,60.0
8,Bob,McDonald,1,FL,18,98.0,65.0

In [55]:
# Rename every column at once
df_students.columns = ['FIRST_NAME', 'LAST_NAME', 'YEAR', 'HOME_STATE', 'STUD_AGE', 'CALC_101_FINAL', 'ENGLISH_101_FINAL']
df_students

,FIRST_NAME,LAST_NAME,YEAR,HOME_STATE,STUD_AGE,CALC_101_FINAL,ENGLISH_101_FINAL
0,Daniel,Smith,1,NY,18,90.0,80.0
1,Ben,Leibstrom,1,NY,19,80.0,NaN
2,Kavita,Kanabar,1,PA,19,NaN,NaN
3,Linda,Thiel,4,CA,22,60.0,40.0
4,Omar,Reichel,2,OK,21,70.0,50.0
5,Jane,OConner,2,HI,19,NaN,NaN
6,Felicia,Rao,3,NY,20,NaN,NaN
7,Rachel,Crock,1,FL,17,NaN,60.0
8,Bob,McDonald,1,FL,18,98.0,65.0

In [56]:
# Change a dataframe's index
df_students.index = ['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8', 'S9']
df_students

,FIRST_NAME,LAST_NAME,YEAR,HOME_STATE,STUD_AGE,CALC_101_FINAL,ENGLISH_101_FINAL
S1,Daniel,Smith,1,NY,18,90.0,80.0
S2,Ben,Leibstrom,1,NY,19,80.0,NaN
S3,Kavita,Kanabar,1,PA,19,NaN,NaN
S4,Linda,Thiel,4,CA,22,60.0,40.0
S5,Omar,Reichel,2,OK,21,70.0,50.0
S6,Jane,OConner,2,HI,19,NaN,NaN
S7,Felicia,Rao,3,NY,20,NaN,NaN
S8,Rachel,Crock,1,FL,17,NaN,60.0
S9,Bob,McDonald,1,FL,18,98.0,65.0

In [57]:
# Reset the index
df_students.reset_index()

,index,FIRST_NAME,LAST_NAME,YEAR,HOME_STATE,STUD_AGE,CALC_101_FINAL,ENGLISH_101_FINAL
0,S1,Daniel,Smith,1,NY,18,90.0,80.0
1,S2,Ben,Leibstrom,1,NY,19,80.0,NaN
2,S3,Kavita,Kanabar,1,PA,19,NaN,NaN
3,S4,Linda,Thiel,4,CA,22,60.0,40.0
4,S5,Omar,Reichel,2,OK,21,70.0,50.0
5,S6,Jane,OConner,2,HI,19,NaN,NaN
6,S7,Felicia,Rao,3,NY,20,NaN,NaN
7,S8,Rachel,Crock,1,FL,17,NaN,60.0
8,S9,Bob,McDonald,1,FL,18,98.0,65.0

In [58]:
# Reset the index without saving the old index, and save
# the dataframe
df_students = df_students.reset_index(drop = True)
df_students

,FIRST_NAME,LAST_NAME,YEAR,HOME_STATE,STUD_AGE,CALC_101_FINAL,ENGLISH_101_FINAL
0,Daniel,Smith,1,NY,18,90.0,80.0
1,Ben,Leibstrom,1,NY,19,80.0,NaN
2,Kavita,Kanabar,1,PA,19,NaN,NaN
3,Linda,Thiel,4,CA,22,60.0,40.0
4,Omar,Reichel,2,OK,21,70.0,50.0
5,Jane,OConner,2,HI,19,NaN,NaN
6,Felicia,Rao,3,NY,20,NaN,NaN
7,Rachel,Crock,1,FL,17,NaN,60.0
8,Bob,McDonald,1,FL,18,98.0,65.0

In [59]:
# Exercise
df_students = df_students.rename(columns = {'STUD_AGE':'AGE'})
df_students

,FIRST_NAME,LAST_NAME,YEAR,HOME_STATE,AGE,CALC_101_FINAL,ENGLISH_101_FINAL
0,Daniel,Smith,1,NY,18,90.0,80.0
1,Ben,Leibstrom,1,NY,19,80.0,NaN
2,Kavita,Kanabar,1,PA,19,NaN,NaN
3,Linda,Thiel,4,CA,22,60.0,40.0
4,Omar,Reichel,2,OK,21,70.0,50.0
5,Jane,OConner,2,HI,19,NaN,NaN
6,Felicia,Rao,3,NY,20,NaN,NaN
7,Rachel,Crock,1,FL,17,NaN,60.0
8,Bob,McDonald,1,FL,18,98.0,65.0

# Lectura de datos

In [77]:

import pandas as pd
import os
os.path.exists("C:/Users/torre/Desktop/Clase Estadistica Aplicada/Datasets/Colab/California_Housing/california_housing_train.csv")
# Read an Excel file into Pandas
#df_housing = pd.read_csv('C:/Users/torre/Desktop/Clase Estadistica Aplicada/Datasets/Colab/California_Housing/california_housing_train.csv')
#df_housing.head()

False

In [69]:
# Read a csv file into pandas


df_census = pd.read_csv('C:/Users/torre/Desktop/Clase Estadistica Aplicada/Datasets/Colab/census.csv')
df_census.columns = ['FIPS', 'GEOGRAPHY', 'POPULATION', 'MEDIAN_AGE',
                       'TOTAL_HOUSEHOLD', 'MEDIAN_HH_INCOME',
                       'AV_HH_SIZE', 'TOTAL_FAMILIES', 'AV_FAMILY_SIZE',
                       'PERC_OWNER_OCCUPIED_HOUSING', 'PERC_RENTER_OCCUPIED_HOUSING',
                       'POP_16_AND_OVER', 'UNEMPLOYMENT_RATE']
df_census.tail(10)

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/torre/Desktop/Clase Estadistica Aplicada/Datasets/Colab/census.csv'

In [35]:
# Read the Dig Inn order file
df_orders = pd.read_csv('/content/simplified_orders.csv')
df_orders.head()

FileNotFoundError: [Errno 2] No such file or directory: '/content/simplified_orders.csv'

In [ ]:
df_orders.shape

In [ ]:
df_orders.info

In [36]:

#Exercise - read in the items file and the restaurants file
df_items = pd.read_csv('/content/items.csv')
df_restaurants = pd.read_csv('/content/restaurants.csv')

FileNotFoundError: [Errno 2] No such file or directory: '/content/items.csv'

In [ ]:
df_items.columns

In [37]:
# Create a function to print the number of rows in a dataframe,
# and then return the first few rows
def explore_df(df):
    print( df.shape[0] )
    return df.head()

In [ ]:
explore_df(df_orders)

In [ ]:
explore_df(df_restaurants)

In [ ]:
explore_df(df_restaurants)

In [ ]:
explore_df(df_restaurants)

In [ ]:
# Print the number of rows in the orders file and the first
# few rows
print( df_restaurants.shape[0] )
df_restaurants.head()

# Tipos de datos de las columnas

In [38]:
# Tell Pandas that the DATETIME column contains a DATETIME
#df_orders.DATETIME = pd.to_datetime(df_orders.DATETIME)
#df_orders.info()

import pandas as pd
# Tell Pandas that the DATETIME column contains a DATETIME
df_orders.DATETIME = pd.to_datetime(df_orders.DATETIME)
df_orders.info()

NameError: name 'df_orders' is not defined

In [ ]:
# Do the same for the columns that need it in df_restaurants
df_restaurants.OPENING_DATE = pd.to_datetime(df_restaurants.OPENING_DATE)
df_restaurants.DELIVERY_START = pd.to_datetime(df_restaurants.DELIVERY_START)

# Guardando datos /Writing Data

In [39]:
# Save the tables we created as pickles, so that we can re-load
# them later
df_census.to_csv('census2.csv')
df_orders.to_pickle('orders.pickle')
df_items.to_pickle('items.pickle')
df_restaurants.to_pickle('restaurants.pickle')

NameError: name 'df_census' is not defined

# Explorando datos; value_counts()

In [40]:
# Find the frequency of each order type
df_orders.TYPE.value_counts()

NameError: name 'df_orders' is not defined

In [ ]:
# Find proportions
df_orders.TYPE.value_counts(normalize = True)

In [ ]:
# Find all the different item types in the df_items dataframe
df_items.ITEM_TYPE.value_counts()

In [ ]:
# Import the Python plotting library
import matplotlib.pyplot as plt

In [ ]:
# Plot the order type proportions
df_orders.TYPE.value_counts(normalize = True).plot(kind = 'bar')

In [ ]:
# Plot the order type proportions
#df_orders.TYPE.value_counts(normalize = True).reset_index().plot(x = 'Type', y = 'TYPE', kind = 'bar')

In [ ]:
# Exercise - find the highest-selling restaurants in our data
df_orders.RESTAURANT_ID.value_counts().plot(kind = 'bar')

# Explorando Datos; Numerical Columns

In [ ]:
# Find summary statistics for the MEDIAN_AGE column
df_census.MEDIAN_AGE.describe()

In [ ]:
# Alternative notation
df_census['MEDIAN_AGE'].describe()

In [ ]:
# Apply describe to every column
df_census.describe()

In [ ]:
# Histogram of MEDIAN_AGE
df_census.MEDIAN_AGE.plot(kind = 'hist')

In [ ]:
# Finer Histogram of MEDIAN_AGE
df_census.MEDIAN_AGE.plot(kind = 'hist', bins = 30)

In [ ]:
# Exercise; apply this to df_order
df_orders.describe()

In [ ]:
# Exercise - income distribution by MSA
df_census.MEDIAN_HH_INCOME.plot(kind = 'hist', bins = 30)

# Operaciones sobre columnas

## Arithmetic

In [ ]:
# Find the population of each MSA in thousands
( df_census.POPULATION / 1000 ).head()

In [ ]:
# Fnd the rough total income per person in each MSA
( df_census.MEDIAN_HH_INCOME / df_census.AV_HH_SIZE ).head()

## Comparaciones valores booleanos

In [ ]:
# Find whether each order has at least one drink
(df_orders.DRINKS >= 1).head()

In [ ]:
# Find all the orders with two cookies exactly
(df_orders.COOKIES == 2).head()

In [ ]:
# Find all orders with at least one drink and two cookies
# exactly
((df_orders.DRINKS >= 1) & (df_orders.COOKIES == 2)).head()

In [ ]:
# Find all orders with at least one drink or two cookies
# exactly
((df_orders.DRINKS >= 1) | (df_orders.COOKIES == 2)).head()

In [ ]:
# Check if each MSA has a population between 20K and 60K
((df_census.POPULATION >= 20000) & (df_census.POPULATION <= 60000)).head()

## Transformaciones / Aggregations

In [ ]:
# Find the total population in our census data
df_census.POPULATION.sum()

In [ ]:
# Find the average number of cookies in each order
df_orders.COOKIES.mean()

In [ ]:
# Find the total number of orders with at least one drink
# AND two cookies exactly
((df_orders.DRINKS >= 1) & (df_orders.COOKIES == 2)).sum()

In [ ]:
# Exercise - find the average household size in the US

# Wrong
df_census.AV_HH_SIZE.mean()

# Right
(df_census['AV_HH_SIZE'] * df_census['TOTAL_HOUSEHOLD']).sum() / df_census['TOTAL_HOUSEHOLD'].sum()

## Busquedad de Múltiples valores; isin()

In [ ]:
# Find whether each row is an order either in R10001 or
# R10002
df_orders.RESTAURANT_ID.isin(['R10001', 'R10002']).head()

## Checking for missing values

In [ ]:
# Find out whether each order is missing a bowl
df_orders.MAIN.isnull().head()

In [ ]:
# Fill missing values with a fixed item
df_orders.MAIN.fillna("No item").head()

In [ ]:
# Exercise - find out the proportion of orders with
# a missing bowl
df_orders.MAIN.isnull().sum() / df_orders.shape[0]

# Or perhaps a better way
df_orders.MAIN.isnull().value_counts(normalize = True)

In [ ]:
# Exercise - create a function that, given a dataframe
# and a column name, prints out the number of null values
# in that column
def print_num_nulls(df, col_name):
    print(f'Column {col_name} has {df[col_name].isnull().sum()} null values')

print_num_nulls(df_orders, 'MAIN')

In [ ]:
# We can do this for every column in the dataframe by looping
# through df_orders' columns.
for i in df_orders:
    print_num_nulls(df_orders, i)

## Datetime columns - Part 1

In [ ]:
# Extract the minute from each datetime
df_orders.DATETIME.dt.minute.head()

In [ ]:
# Check we got it right
df_orders.head()

In [ ]:
# Find the weekday of each date in the DATETIME column
df_orders.DATETIME.dt.weekday.head()

In [ ]:
# Exercise - sales by day of week
df_orders.DATETIME.dt.weekday.value_counts().plot(kind = 'bar')

In [ ]:
# Exercise - another way
for i in range(7):
    print(f'Day {i} has {(df_orders.DATETIME.dt.weekday == i).sum()} sales')

## Datetime columns - Part 2

In [ ]:
# Find all orders after June 1st 2018
(df_orders.DATETIME >= '2018-06-01').sum()

In [ ]:
# Find all orders on June 1st 2018
( (df_orders.DATETIME >= '2018-06-01') & (df_orders.DATETIME <= '2018-06-02') ).sum()

## The .apply function

In [ ]:
%%time
# Add one to each drink number, using apply
def add_one(x):
    return x+1

df_orders.DRINKS.apply(add_one).head()

In [ ]:
%%time
# Add one to each drink number directly
(df_orders.DRINKS + 1).head()

# Filtering Data

In [ ]:
# Find all orders with drinks
df_orders[df_orders.DRINKS > 0].head()

In [ ]:
# Compare the shape of the original data to the shape
# of this new dataframe
print(df_orders.shape)
print(df_orders[df_orders.DRINKS > 0].shape)